services:
  backend:
    build: ./backend
    container_name: travix-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - playwright
    networks:
      - travix-net

  playwright:
    build: ./playwright
    container_name: travix-playwright
    volumes:
      - ./playwright:/app
    networks:
      - travix-net

  db:
    image: postgres:14
    container_name: travix-db
    environment:
      POSTGRES_USER: travian
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: travian
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - travix-net

networks:
  travix-net:
    driver: bridge

volumes:
  pgdata:
